/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.camila.pe.cpresentacion;

/**
 *
 * @author Alumno-PB203
 */
public class calculadora extends javax.swing.JPanel {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 40));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 253, -1, 45));
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 253, -1, 45));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 253, -1, 45));
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 253, -1, 45));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 150, 320, 57));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 316, -1, 45));
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 316, -1, 45));
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 316, -1, 45));
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 316, -1, 45));
        add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 442, -1, 45));
        add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 379, -1, 45));
        add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 379, -1, 45));
        add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 379, -1, 45));
        add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 379, -1, 45));
        add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 442, -1, 45));
        add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 505, -1, 45));
        add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 505, -1, 45));
        add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 505, -1, 45));
        add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 442, -1, 45));
        add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 442, -1, 45));
        add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 505, -1, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
